services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes: # we can store the files in the host machine instead of the container
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    env_file: .env # non sensitive data
    secrets:
      - db_user_password
      - db_root_password
    environment:
      DB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      DB_USER_PASSWORD_FILE: /run/secrets/db_user_password

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped
    env_file: .env
    secrets:
      - db_user_password
      - db_root_password
      - wp_admin_credentials
      - wp_user_credentials
    environment:
      DB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      DB_USER_PASSWORD_FILE: /run/secrets/db_user_password
      WP_ADMIN_CREDENTIALS_FILE: /run/secrets/wp_admin_credentials
      WP_USER_CREDENTIALS_FILE: /run/secrets/wp_user_credentials

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: unless-stopped
    env_file: .env

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_credentials:
    file: ../secrets/wp_admin_credentials.txt
  wp_user_credentials:
    file: ../secrets/wp_user_credentials.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

networks:
  inception:
